spring.application.name=ecommerce_application

spring.datasource.url=jdbc:mysql://host.docker.internal:3306/ecommerce_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=8080